<Project>
  <Import Project="$(MSBuildThisFileDirectory)build\GtkSharp.targets" />
  <Import Project="$(MSBuildThisFileDirectory)build\RestoredMonoDevelop.targets" />
  <PropertyGroup>
    <OutputPath>$(OutDir)</OutputPath>
  </PropertyGroup>
  <Target Name="CopyDllsToOutputDir" AfterTargets="Build">
    <ItemGroup>
      <SourceProjectFiles Include="$(MSBuildThisFileDirectory)**\*.csproj" Exclude="$(MSBuildThisFileDirectory)bin\**\*;$(MSBuildThisFileDirectory)obj\**\*" />
      <SourceProjectDlls Include="@(SourceProjectFiles->'$(MSBuildThisFileDirectory)dlls\%(Filename).dll')" />
      <DllFiles Include="$(MSBuildThisFileDirectory)dlls\*.dll" />
      <DllFiles Remove="@(SourceProjectDlls)" />
      <DllFiles Remove="$(MSBuildThisFileDirectory)dlls\Mono.Debugging.dll;$(MSBuildThisFileDirectory)dlls\MonoDevelop.Debugger.dll;$(MSBuildThisFileDirectory)dlls\MonoDevelop.SourceEditor2.dll" Condition="'$(UseRestoredMonoDevelop)' == 'true'" />
      <DllFiles Remove="$(MSBuildThisFileDirectory)dlls\CocoStudio.WindowsPlatform.dll" Condition="'$(UseRestoredMonoDevelop)' == 'true'" />
      <RuntimeAssetFiles Include="$(MSBuildThisFileDirectory)runtime-assets\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(DllFiles)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(RuntimeAssetFiles)" DestinationFiles="@(RuntimeAssetFiles->'$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
