<Project>
  <PropertyGroup>
    <OutputPath>$(OutDir)</OutputPath>
  </PropertyGroup>
  <Target Name="CopyDllsToOutputDir" AfterTargets="Build">
    <ItemGroup>
      <SourceProjectFiles Include="$(MSBuildThisFileDirectory)**\*.csproj" Exclude="$(MSBuildThisFileDirectory)bin\**\*;$(MSBuildThisFileDirectory)obj\**\*" />
      <SourceProjectDlls Include="@(SourceProjectFiles->'$(MSBuildThisFileDirectory)dlls\%(Filename).dll')" />
      <DllFiles Include="$(MSBuildThisFileDirectory)dlls\*.dll" />
      <DllFiles Remove="@(SourceProjectDlls)" />
      <RuntimeAssetFiles Include="$(MSBuildThisFileDirectory)runtime-assets\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(DllFiles)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(RuntimeAssetFiles)" DestinationFiles="@(RuntimeAssetFiles->'$(OutDir)%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>
</Project>
