
# Please keep this gtkrc in sync with the other ones from Clearlooks based themes.

gtk-color-scheme = 
"base_color:#fff
fg_color:#333
tooltip_fg_color:#666
selected_bg_color:#fff
selected_fg_color:#888
text_color:#333
bg_color:#fff
tooltip_bg_color:#fff
blue_bg:#1db5f2"

gtk-button-images = 0

style "default" {
	xthickness = 1
	ythickness =1 

	#######################
	# Style Properties
	#######################
	GtkButton::child-displacement-x = 1
	GtkButton::child-displacement-y = 1
	GtkButton::default-border = { 0, 0, 0, 0 }
	GtkButton::image-spacing = 4
	GtkToolButton::icon-spacing = 4

	GtkCheckButton::indicator-size = 14

	GtkPaned::handle-size = 6

	GtkRange::trough-border = 0
	GtkRange::slider-width = 15
	GtkRange::stepper-size = 15
    GtkScrolledWindow::scrollbar-spacing = 0

	GtkScale::slider-length = 23
	GtkScale::trough-side-details = 1

	GtkScrollbar::min-slider-length = 10
	GtkScrollbar::slider_width = 10
	GtkScrollbar::has-backward-stepper = 0
	GtkScrollbar::has-forward-stepper = 0

	GtkMenuBar::internal-padding = 0
	GtkExpander::expander-size = 10
	GtkToolbar::internal-padding = 1
	GtkTreeView::expander-size = 10
	GtkTreeView::vertical-separator = 0

	GtkMenu::horizontal-padding =2
    GtkMenu::vertical-padding = 0
    GtkMenuItem::arrow-scaling = 0.5
    GtkMenuItem::horizontal-padding = 4

	GtkComboBox::arrow-size = 0
    GtkComboBox::arrow-scaling = 0.2

	WnckTasklist::fade-overlay-rect = 0
	# The following line hints to gecko (and possibly other appliations)
	# that the entry should be drawn transparently on the canvas.
	# Without this, gecko will fill in the background of the entry.
	#GtkEntry::honors-transparent-bg-hint = 1

	GtkEntry::progress-border = { 1, 1, 1, 1 }
	font_name = "Lucida Grande 11"

	####################
	# Color Definitions
	####################
	bg[NORMAL]        = @bg_color
	bg[PRELIGHT]      = shade (1.02, @bg_color)
	bg[SELECTED]      = @selected_bg_color
	bg[INSENSITIVE]   = @bg_color
	bg[ACTIVE]        = shade (0.9, @bg_color)

	fg[NORMAL]        = @fg_color
	fg[PRELIGHT]      = @fg_color
	fg[SELECTED]      = @selected_fg_color
	fg[INSENSITIVE]   = darker (@bg_color)
	fg[ACTIVE]        = @fg_color

	text[NORMAL]      = @text_color
	text[PRELIGHT]    = @text_color
	text[SELECTED]    = @selected_fg_color
	text[INSENSITIVE] = darker (@bg_color)
	text[ACTIVE]      = @selected_fg_color

	base[NORMAL]      = @base_color
	base[PRELIGHT]    = shade (0.95, @bg_color)
	base[SELECTED]    = @selected_bg_color
	base[INSENSITIVE] = @bg_color
	base[ACTIVE]      = shade (0.9, @selected_bg_color)

	engine "clearlooks" {
		#colorize_scrollbar = TRUE
		reliefstyle = 1
		menubarstyle = 0
		toolbarstyle = 0
		animation = FALSE
		disable_focus = TRUE
		radius = 3.0
		style = GLOSSY

		# Set a hint to disable backward compatibility fallbacks.
		hint = "use-hints"
	}
}

style "text_widget"
{
    base[NORMAL]      = "#414141"
    bg[NORMAL] = "#444444"
}

style "wide" {
	xthickness = 2
	ythickness = 2
}

style "wider" {
	xthickness = 3
	ythickness = 3
}

style "white_entry" = "text_widget" {
	xthickness = 0
	ythickness = 0

	bg[SELECTED] = mix (0.4, @selected_bg_color, @base_color)
	fg[SELECTED] = "#888"
    bg[SELECTED] = "#888"
    base[NORMAL] = "#fff"
    base[SELECTED] = "#5acaf7"
	text[SELECTED] = "#333"
    base[PRELIGHT] = "#f00"
    base[INSENSITIVE] = "#f6f6f6"
	engine "clearlooks" {
        #focus_color = shade (0.65, @selected_bg_color)
		focus_color = "#0f0"
	}
}

style "gray_entry" = "text_widget" {
	xthickness = 0
	ythickness = 0

	bg[SELECTED] = mix (0.4, @selected_bg_color, @base_color)
	fg[SELECTED] = "#888"
    bg[SELECTED] = "#888"
    base[NORMAL] = "#f8f8f8"
    base[SELECTED] = "#5acaf7"
	text[SELECTED] = "#333"
    base[INSENSITIVE] = "#f6f6f6"
	engine "clearlooks" {
        #focus_color = shade (0.65, @selected_bg_color)
		focus_color = "#0f0"
	}
}

style "entry" {
    xthickness = 4
    ythickness = 4
    bg[NORMAL] = @base_color
	
#	bg[SELECTED] = mix (0.4, @selected_bg_color, @base_color)
	#底色
    base[NORMAL] = "#fff"
	#文字被选中时的底色
    base[SELECTED] = "#5acaf7"
	#文字被选中时的颜色
	text[SELECTED] = "#333"
	
	engine "clearlooks" {
		#colorize_scrollbar = TRUE
		reliefstyle = 1
		menubarstyle = 0
		toolbarstyle = 0
		animation = FALSE
        #输入框有焦点时边框颜色
		disable_focus = FALSE
		focus_color = "#1FA5EE"
		
		radius = 4.0
#		style = GLOSSY

	}
}

style "textView" {
	#文字被选中时的底色
    base[SELECTED] = "#5acaf7"

	#文字被选中时的颜色
	text[SELECTED] = "#333"
}

style "spinbutton" {
    bg[NORMAL] = "#444444"

	engine "clearlooks" {
		hint = "spinbutton"
	}
}

style "scale" {
	xthickness = 2
	ythickness = 2

	engine "clearlooks" {
		hint = "scale"
	}
}

style "vscale" {

	engine "clearlooks" {
		hint = "vscale"
	}
}

style "hscale" {

	engine "clearlooks" {
		hint = "hscale"
	}
}

style "scrollbar" {
	xthickness =0
	ythickness =0
	engine "clearlooks" {
		hint = "scrollbar"
	}
}

style "hscrollbar" {

	engine "clearlooks" {
		hint = "hscrollbar"
	}
}

style "vscrollbar" {

	engine "clearlooks" {
		hint = "vscrollbar"
	}
}

style "notebook_bg" {

	bg[NORMAL]        = shade (1.02, @bg_color)
}

style "button" {
	xthickness = 3
	ythickness = 3


	bg[NORMAL]        = @bg_color
	bg[PRELIGHT]      = shade (1.5, @bg_color)
	bg[ACTIVE]        = shade (1.5, @bg_color)
    	bg[INSENSITIVE]   = shade(1.5,@bg_color)
}

# The color is changed by the notebook_bg style, this style
# changes the x/ythickness
style "notebook" {
	xthickness = 3
	ythickness = 3
}

style "statusbar" {

	engine "clearlooks" {
		hint = "statusbar"
	}
}

style "comboboxentry" {

	engine "clearlooks" {
		# Note:
		# If you set the appears-as-list option on comboboxes in the theme,
		# then you should set this hint on the combobox instead.
		hint = "comboboxentry"
	}
}

style "menubar" {

	engine "clearlooks" {
		hint = "menubar"
	}
}

style "menu" {
	xthickness = 0
	ythickness = 6
}

style "menu_item" {
	xthickness = 7
	ythickness = 3
	fg[PRELIGHT]      = @selected_bg_color
    bg[PRELIGHT]      = @blue_bg
    engine "svg"
    {

    }
}

# This style is there to modify the separator menu items. The goals are:
# 1. Get a specific height.
# 2. The line should go to the edges (ie. no border at the left/right)
style "separator_menu_item" {
	xthickness = 1
	ythickness = 0

	GtkSeparatorMenuItem::horizontal-padding = 0
	GtkWidget::wide-separators = 1
	GtkWidget::separator-width = 1
	GtkWidget::separator-height = 7
}

style "frame_title" {

	fg[NORMAL]        = lighter (@fg_color)
}

style "treeview" {

    base[ACTIVE] = @base_color
    base[NORMAL] = @base_color
    base[PRELIGHT] = "#ff0000"
    base[SELECTED] = @blue_bg
    base[INSENSITIVE] = @blue_bg

   GtkTreeView::even-row-color =@base_color
    GtkTreeView::odd-row-color = @blue_bg
    engine "svg"
    {
	    image
        {
          function = FOCUS
        } 
    }
}

style "theme-dark-tree"
{
    xthickness = 0
    ythickness = 0

	base[ACTIVE]      = @blue_bg
	text[SELECTED]    = @base_color
	text[ACTIVE]    = @base_color

    GtkTreeView::even-row-color = @base_color
    GtkTreeView::odd-row-color = @blue_bg
    engine "svg"
    {
	    image
        {
          function = FOCUS
        } 
    }
}

# The almost useless progress bar style
style "progressbar" {
	
    bg[SELECTED]= "#00b4f5"
	bg[NORMAL] = "#f5f5f5"
	
	xthickness = 0
	ythickness = 0
    engine "clearlooks" {
        # Explicitly set the radius for the progress bars inside menu items.
          radius =2.0

        hint = "progressbar"
    }
}

style "progressbar_Black" {
	
    bg[SELECTED]= "#00b4f5"
	bg[NORMAL] = "#060e17"
	
	xthickness = 0
	ythickness = 0
    engine "clearlooks" {
        # Explicitly set the radius for the progress bars inside menu items.
        radius = 0.0

        hint = "progressbar"
    }
}


# This style is based on the default style, so that the colors from the button
# style are overriden again.
style "treeview_header" = "default" {
	xthickness = 2
	ythickness = 1

	engine "clearlooks" {
		hint = "treeview-header"
	}
}

style "tooltips" {
	xthickness = 4
	ythickness = 4

	bg[NORMAL]        = @tooltip_bg_color
	fg[NORMAL]        = @tooltip_fg_color
}

style "nautilus_location" {

	bg[NORMAL]        = mix (0.60, shade (1.05, @bg_color), @selected_bg_color)
}

# Wrokaroudn style for places where the text color is used instead of the fg color.
style "text_is_fg_color_workaround" {

	text[NORMAL]      = @fg_color
	text[PRELIGHT]    = @fg_color
	text[SELECTED]    = @selected_fg_color
	text[ACTIVE]      = @fg_color
	text[INSENSITIVE] = darker (@bg_color)
}

# Workaround style for menus where the text color is used instead of the fg color.
style "menuitem_text_is_fg_color_workaround" {

	text[NORMAL]      = @fg_color
	text[PRELIGHT]    = @text_color
	text[SELECTED]    = @selected_fg_color
	text[ACTIVE]      = @fg_color
	text[INSENSITIVE] = darker (@bg_color)
	bg[SELECTED]      = "#00b4f5"
}

# Workaround style for places where the fg color is used instead of the text color.
style "fg_is_text_color_workaround" {

	fg[NORMAL]        = @text_color
	fg[PRELIGHT]      = @text_color
	fg[SELECTED]      = @selected_fg_color
	fg[ACTIVE]        = @selected_fg_color
	fg[INSENSITIVE]   = darker (@bg_color)
}

# Style to set the toolbar to use a flat style. This is because the "New" button in
# Evolution is not drawn transparent. So if there is a gradient in the background it will
# look really wrong.
# See http://bugzilla.gnome.org/show_bug.cgi?id=446953.
style "evo_new_button_workaround" {

	engine "clearlooks" {
		toolbarstyle = 0
	}
}

style "checkbox" {
    base[NORMAL] = "#fff"
    bg[SELECTED] = "#fff"

	text[NORMAL] = "#17adea"
	engine "clearlooks" {
	#hint = "checkbox"
	}
}

###############################################################################
# The following part of the gtkrc applies the different styles to the widgets.
###############################################################################

# The default style is applied to every widget
class "GtkWidget" style "default"

class "GtkSeparator" style "wide"
class "GtkFrame" style "wide"
class "GtkCalendar" style "wide"
class "GtkEntry" style "entry"
class "GtkTextView" style "textView"

class "GtkSpinButton" style "spinbutton"
class "GtkScale" style "scale"
class "GtkVScale" style "vscale"
class "GtkHScale" style "hscale"
class "GtkScrollbar" style "scrollbar"
class "GtkHScrollbar" style "hscrollbar"
class "GtkVScrollbar" style "vscrollbar"
class "GtkProgressBar" style "progressbar"
widget "*ProgressbarBg_Black" style "progressbar_Black"
widget "*WhiteEntry" style "white_entry"
widget "*GrayEntry" style "gray_entry"
widget "*DarkTreeView" style "theme-dark-tree"

# General matching follows. The order is choosen so that the right styles override
# each other. EG. progressbar needs to be more important than the menu match.
widget_class "*<GtkNotebook>" style "notebook_bg"
# This is not perfect, it could be done better.
# (That is modify *every* widget in the notebook, and change those back that
# we really don't want changed)
widget_class "*<GtkNotebook>*<GtkEventBox>" style "notebook_bg"
widget_class "*<GtkNotebook>*<GtkDrawingArea>" style "notebook_bg"
widget_class "*<GtkNotebook>*<GtkLayout>" style "notebook_bg"
widget_class "*<GtkNotebook>*<GtkViewport>" style "notebook_bg"
widget_class "*<GtkNotebook>*<GtkScrolledWindow>" style "notebook_bg"

widget_class "*<GtkButton>" style "button"
widget_class "*<GtkNotebook>" style "notebook"
widget_class "*<GtkStatusbar>*" style "statusbar"

widget_class "*<GtkComboBoxEntry>*" style "comboboxentry"

widget_class "*<GtkMenuBar>*" style "menubar"
widget_class "*<GtkMenu>*" style "menu"
widget_class "*<GtkMenuItem>*" style "menu_item"
widget_class "*<GtkSeparatorMenuItem>*" style "separator_menu_item"

widget_class "*.<GtkFrame>.<GtkLabel>" style "frame_title"
widget_class "*.<GtkTreeView>*" style "treeview"


#-------------------xiaoqiang-----------------------------------------------------------------
widget_class "*<GtkCheckButton>" style "checkbox"

# Treeview headers (and similar stock GTK+ widgets)
widget_class "*.<GtkTreeView>.<GtkButton>" style "treeview_header"
widget_class "*.<GtkCTree>.<GtkButton>" style "treeview_header"
widget_class "*.<GtkList>.<GtkButton>" style "treeview_header"
widget_class "*.<GtkCList>.<GtkButton>" style "treeview_header"

# The window of the tooltip is called "gtk-tooltip"
##################################################################
# FIXME:
# This will not work if one embeds eg. a button into the tooltip.
# As far as I can tell right now we will need to rework the theme
# quite a bit to get this working correctly.
# (It will involve setting different priorities, etc.)
##################################################################
widget "gtk-tooltip*" style "tooltips"

##########################################################################
# Following are special cases and workarounds for issues in applications.
##########################################################################

# Workaround for the evolution ETable (bug #527532)
widget_class "*.<ETable>.<ECanvas>" style "treeview_header"
# Workaround for the evolution ETree
widget_class "*.<ETree>.<ECanvas>" style "treeview_header"

# Special case the nautilus-extra-view-widget
# ToDo: A more generic approach for all applications that have a widget like this.
widget "*.nautilus-extra-view-widget" style : highest "nautilus_location"

# Work around for http://bugzilla.gnome.org/show_bug.cgi?id=382646
# Note that this work around assumes that the combobox is _not_ in appears-as-list mode.
# This is the part of the workaround that fixes the menus
widget "*.gtk-combobox-popup-menu.*" style "menuitem_text_is_fg_color_workaround"

# Work around the usage of GtkLabel inside GtkListItems to display text.
# This breaks because the label is shown on a background that is based on the base color.
widget_class "*<GtkListItem>*" style "fg_is_text_color_workaround"
# GtkCList also uses the fg color to draw text on top of the base colors.
widget_class "*<GtkCList>" style "fg_is_text_color_workaround"
# Nautilus when renaming files, and maybe other places.
widget_class "*<EelEditableLabel>" style "fg_is_text_color_workaround"

# See the documentation of the style.
widget_class "EShellWindow.GtkVBox.BonoboDock.BonoboDockBand.BonoboDockItem*" style "evo_new_button_workaround"

###########################
#customstyle
###########################
style "coco_scroll"
{
    xthickness = 0
    ythickness = 0
}

class "GtkScrolledWindow" style "coco_scroll"

