
# Please keep this gtkrc in sync with the other ones from Clearlooks based themes.
gtk-color-scheme = "base_color:#323236\nfg_color:#fff\ntooltip_fg_color:#fff\nselected_bg_color:#0872f5\nselected_fg_color:#ffffff\ntext_color:#ffffff\nbg_color:#414146\ntooltip_bg_color:#414146\ndarkbg_color:#252526"

gtk-button-images = 0

style "default" {
	xthickness = 0
    ythickness = 0

	#######################
	# Style Properties
	#######################
	GtkButton::child-displacement-x = 0
    GtkButton::child-displacement-y = 0
    GtkButton::default-border = {0,0,0,0}

    GtkButton::disable_focus = False
    GtkButton::image-spacing = 4
    GtkToolButton::icon-spacing = 4

    GtkCheckButton::indicator-size = 14

    GtkPaned::handle-size = 6

    GtkRange::trough-border = 0
    GtkRange::slider-width = 15
    GtkRange::stepper-size = 15
	GtkScrolledWindow::scrollbar-spacing = 0

    GtkScale::slider-length = 15
    GtkScale::trough-side-details = 10
    GtkScale::activate-slide = False

    GtkScrollbar::min-slider-length = 15
    GtkScrollbar::slider_width = 9
    GtkScrollbar::has-backward-stepper = 0
    GtkScrollbar::has-forward-stepper = 0
    

    GtkProgress::xspacing = 0
    GtkProgress::min-horizontal-bar-height = 5


    GtkMenuBar::internal-padding = 0
    GtkExpander::expander-size = 10
    GtkExpander::label-fill = True
    GtkToolbar::internal-padding = 1
    GtkTreeView::expander-size = 10
    GtkTreeView::vertical-separator = 0

    GtkMenu::horizontal-padding =2
    GtkMenu::vertical-padding = 0
    GtkMenuItem::arrow-scaling = 0.5
    GtkMenuItem::horizontal-padding = 4

    GtkComboBox::arrow-size = 0
    GtkComboBox::arrow-scaling = 0.4

    WnckTasklist::fade-overlay-rect = 0
    # The following line hints to gecko (and possibly other appliations)
    # that the entry should be drawn transparently on the canvas.
    # Without this, gecko will fill in the background of the entry.
    #GtkEntry::honors-transparent-bg-hint = 1

    GtkEntry::progress-border = { 0, 0, 0, 0}
	font_name = "Lucida Grande 12"

	####################
	# Color Definitions
	####################
    bg[NORMAL]        = @bg_color
    bg[PRELIGHT]      = shade (1.02, @bg_color)
    bg[SELECTED]      = @selected_bg_color
    bg[INSENSITIVE]   = shade(1.02,@bg_color)
    bg[ACTIVE]        = shade (0.9, @bg_color)

    fg[NORMAL]        = @fg_color
    fg[PRELIGHT]      = @fg_color
    fg[SELECTED]      = @selected_fg_color
    fg[INSENSITIVE]   ="#a5a8b0"
    fg[ACTIVE]        = @fg_color

    text[NORMAL]      = @text_color
    text[PRELIGHT]    = @text_color
    text[SELECTED]    = @selected_fg_color
    text[INSENSITIVE] = "#a5a8b0"
    text[ACTIVE]      = @selected_fg_color

    base[NORMAL]      = @base_color
    base[PRELIGHT]    = shade (0.95, @bg_color)
    base[SELECTED]    = @selected_bg_color
    base[INSENSITIVE] = shade(0.95,@bg_color)
    base[ACTIVE]      = shade (0.9, @selected_bg_color)

    engine "clearlooks" {
        colorize_scrollbar = TRUE
        scrollbar_color = "#424147"
        reliefstyle = 1
        menubarstyle = 0
        toolbarstyle = 0
        disable_focus = TRUE
        animation = FALSE
        radius = 0.0
        style = GLOSSY
        contrast = 1.0
        # Set a hint to disable backward compatibility fallbacks.
        #hint = "use-hints"
    }

   
}

style "text_widget" = "default"
{
    xthickness = 2
    ythickness = 2
    engine "clearlooks" 
    {
        disable_focus = FALSE
        focus_color = "#0872f5"
        hint = "entry"

    }
}

style "password_entry" = "default"
{
    xthickness = 2
    ythickness = 2
    engine "clearlooks" 
    {
        disable_focus = FALSE
        focus_color = "#0872f5"
        hint = "entry"

    }
}

style "noBorder_entry" = "text_widget" {
	xthickness = 0
	ythickness = 0
}

style "button" = "default"
{
    xthickness = 0
    ythickness = 0
    bg[NORMAL] = "#65676E"
    bg[PRELIGHT] = shade(1.2,"#65676E")
    bg[ACTIVE] = shade(0.9,"#65676E")
    bg[INSENSITIVE] = shade(0.9,"#65676E")
    engine "svg"
    {
        image
        {
          function = FOCUS
        } 
    }
}
style "main_button" = "default"
{
    xthickness = 0
    ythickness = 0
    bg[NORMAL] = "#0872f5"
    bg[PRELIGHT] ="#1668cc"
    bg[ACTIVE] = "#075ac0"
    bg[INSENSITIVE] = "#3c3b40"
    engine "svg"
    {
	    image
        {
          function = FOCUS
        } 
    }
}
style "spinbutton" {
    xthickness = 2
    ythickness = 2
    engine "clearlooks" 
    {
        disable_focus = FALSE
        focus_color = "#0872f5"
        hint = "entry"
    }
}

style "checkbutton" = "default"
{
    text[NORMAL] = "#0872f5"
    bg[SELECTED]    = @bg_color
    base[ACTIVE]      = shade (0.9, @bg_color)
    base[NORMAL]      = shade (0.9, @bg_color)
}

style "checkbutton_white"
{
    text[NORMAL] = "#fff"
    bg[SELECTED]    = @bg_color
    base[ACTIVE]      = shade (0.9, @bg_color)
    base[NORMAL]      = shade (0.9, @bg_color)
}

style "scrollbar"
{
    xthickness = 0
    ythickness = 0
    GtkRange::slider-width = 16
    GtkRange::trough-border = 2
    bg[NORMAL] =  "#56565b"
    bg[PRELIGHT] =  shade(1.2,"#56565b")
 #  engine "mist"
 #  {
 #
 #  }
}


style "menubar"  = "default"{
    xthickness = 0
    ythickness = 0
 #   engine "mist"
 #   {
 #   
 #   }
}

style "menu" {
    xthickness = 0
    ythickness = 6
 #   engine "mist"
 #   {
 #
 #   }
}
style "cs_imagebutton"
{
    bg[INSENSITIVE] = "#ff0"
    bg[NORMAL] = "#f00"
}

style "menu_item" {

    xthickness = 7
    ythickness = 3

    fg[PRELIGHT]      = @selected_fg_color
    bg[PRELIGHT]      = @selected_bg_color
        engine "svg"
    {
    }

}


# This style is there to modify the separator menu items. The goals are:
# 1. Get a specific height.
# 2. The line should go to the edges (ie. no border at the left/right)
style "separator_menu_item" {
    xthickness = 0
    ythickness = 0
    bg[NORMAL] = "#3b3a40"
    GtkSeparatorMenuItem::horizontal-padding = 2
    GtkWidget::wide-separators = 1
    GtkWidget::separator-width = 1
    GtkWidget::separator-height = 1
}

style "progressbar" {
    xthickness = 1
    ythickness = 2
    fg[PRELIGHT]      = @selected_fg_color

    engine "clearlooks" {
        # Explicitly set the radius for the progress bars inside menu items.
        radius = 0.0

        hint = "progressbar"
    }
}
style "separator"
{
    fg[NORMAL] = "#FF0"
    bg[NORMAL] = "#212123"
}

style "coco_expander"
{
    bg[NORMAL] = "#7c7e86"
    base[NORMAL] = "#7c7e86"
    fg[NORMAL] = "#7c7e86"
   engine "clearlooks" {
       hint = "expander"
   }
}

style "dialog_button"
{
    #bg[SELECTED] = "#65676E"
        engine "clearlooks" {
        focus_color="#ff0"
    }
}
style "combo"
{
    xthickness = 0
    ythickness = 0
    bg[NORMAL] = "#323236"
	bg[PRELIGHT] = shade(1.1,"#323236")
	fg[NORMAL] = "#a5a8b0"
	fg[PRELIGHT] = shade(1.2,"#a5a8b0")
    engine "svg"
    {
	    image
        {
          function = FOCUS
        } 
    }
}

style "main_combo"
{
    xthickness = 0
    ythickness = 0
    bg[NORMAL] = "#28282a"
	bg[PRELIGHT] = shade(1.1,"#28282a")
    fg[NORMAL] = "#a5a8b0"
	fg[PRELIGHT] = shade(1.2,"#a5a8b0")

    #svg样式引擎在禁用状态会有白色的阴影
    #engine "svg"
    #{
    #    image
    #    {
    #      function = FOCUS
    #    } 
    #}

    engine "clearlooks" 
    {
        disable_focus = TRUE
        focus_color = "#0872f5"
        hint = "entry"
    }
}

style "combo_entry"
{
    xthickness = 2
    ythickness = 0
    engine "clearlooks" 
    {
        disable_focus = TRUE
        focus_color = "#0872f5"
        hint = "entry"
    }
}
style "combo_entry_entry"
{
    # xthickness = 0
    # ythickness = 0
    fg[NORMAL] = "#0f0"
    # fg[NORMAL] = "#abaeb8"
    bg[NORMAL] = @base_color
    bg[INSENSITIVE] = @base_color
    # base[NORMAL] = "#0f0"
    # text[NORMAL] = "#00F"
    engine "clearlooks" 
    {
        disable_focus = FALSE
        focus_color = "#0872f5"
        hint = "entry"
    }
}
style "theme-tree"
{
    xthickness = 0
    ythickness = 0

    GtkTreeView::even-row-color =@bg_color
    GtkTreeView::odd-row-color = @bg_color
    engine "svg"
    {
	    image
        {
          function = FOCUS
        } 
    }
}
style "theme-dark-tree"
{
    xthickness = 0
    ythickness = 0

    GtkTreeView::even-row-color =@darkbg_color
    GtkTreeView::odd-row-color = @darkbg_color
    engine "svg"
    {
	    image
        {
          function = FOCUS
        } 
    }
}
style "scroll"
{
#    engine "mist"
#    {
#    }
}
style "inactivetext"
{

    engine "murrine"
    {
    }
}

style "tooltips" {
	xthickness =4
	ythickness =2

	bg[NORMAL]        = @tooltip_bg_color
	fg[NORMAL]        = @tooltip_fg_color
}

class "*" style "default"
class "GtkEntry" style "text_widget"
widget "*PasswordEntry" style "password_entry"
widget "*NoBorderEntry" style "noBorder_entry"
class "GtkButton" style "button"
widget "*DefaultButton" style "button"
widget "*MainButton" style "main_button"
class "GtkSpinButton" style "spinbutton"
class "GtkProgressBar" style "progressbar"
class "GtkHSeparator" style "separator"
class "GtkVSeparator" style "separator"
class "GtkTreeView" style "theme-tree"
widget "*DarkTreeView" style "theme-dark-tree"
class "*ExtendTreeView" style "theme-tree"
class "*ContextMenuTreeView" style "theme-tree"
class "GtkExpander" style "coco_expander"
class "GtkArrow" style "coco_expander"
class "GtkScrolledWindow " style "scroll"
class "GtkViewPort " style "scroll"
widget "gtk-tooltip*" style "tooltips"
#
#
widget_class "*.<GtkCheckButton>" style "checkbutton"
widget "*WhiteCheckButton" style "checkbutton_white"
widget_class "*.<GtkScrollbar>" style "scrollbar"
#
widget_class "*<GtkMenuBar>*" style "menubar"
#widget_class "*<GtkMenu>*" style "menu"
widget_class "*<GtkMenuItem>*" style "menu_item"
##widget_class "*<GtkCheckMenuItem>.*" style "checkmenuitem"
widget_class "*<GtkSeparatorMenuItem>*" style "separator_menu_item"
#
##widget_class "*<*CSImageButton>.<GtkButton>" style "cs_imagebutton"
##widget_class "*GtkExpander.<GtkLabel>" style "coco_expander"
#widget_class "*.<GtkExpander>" style "coco_expander"
##widget_class "*.*" style "coco_expander"
#widget_class "*ExtendTreeView.*.<GtkExpander>" style "coco_expander"
#
##widget_class "*<GtkMessageDialog>.*.<GtkButton>" style "dialog_button"
widget_class "*<GtkComboBox>.*" style "combo"
widget "*MainComboBox*" style "main_combo"
widget_class "*<GtkComboBoxEntry>.*" style "combo_entry"
widget_class "*<GtkComboBoxEntry>.<GtkEntry>" style "combo_entry_entry"

#widget_class "*<GtkCheckMenuItem>.*" style "checkmenuitem"
#
#widget_class "*.GtkTreeView.GtkButton" style "theme-tree"
#widget_class "*.GtkCTree.GtkButton"     style "theme-tree"
#widget_class "*.GtkList.GtkButton"  style "theme-tree"
#widget_class "*.GtkCList.GtkButton"     style "theme-tree"
##widget_class "*.GtkFrame.GtkLabel"  style "theme-frame-title"


widget_class "*.<GtkLabel>" style "inactivetext"
widget_class "*.<GtkCellLayout>" style "inactivetext"
#widget_class "*.<GtkMenuItem>.*" style "inactivetext"
widget_class "*.<GtkArrow>.*" style "inactivetext"
#class "*" style "inactivetext"