using System;

namespace OpenDialogs
{
	public enum ButtonStyle : long
	{
		BS_PUSHBUTTON,
		BS_DEFPUSHBUTTON,
		BS_CHECKBOX,
		BS_AUTOCHECKBOX,
		BS_RADIOBUTTON,
		BS_3STATE,
		BS_AUTO3STATE,
		BS_GROUPBOX,
		BS_USERBUTTON,
		BS_AUTORADIOBUTTON,
		BS_PUSHBOX,
		BS_OWNERDRAW,
		BS_TYPEMASK = 15L,
		BS_LEFTTEXT = 32L,
		BS_TEXT = 0L,
		BS_ICON = 64L,
		BS_BITMAP = 128L,
		BS_LEFT = 256L,
		BS_RIGHT = 512L,
		BS_CENTER = 768L,
		BS_TOP = 1024L,
		BS_BOTTOM = 2048L,
		BS_VCENTER = 3072L,
		BS_PUSHLIKE = 4096L,
		BS_MULTILINE = 8192L,
		BS_NOTIFY = 16384L,
		BS_FLAT = 32768L,
		BS_RIGHTBUTTON = 32L
	}
}
