using System;

namespace OpenDialogs
{
	public enum ComboBoxStyles : long
	{
		CBS_SIMPLE = 1L,
		CBS_DROPDOWN,
		CBS_DROPDOWNLIST,
		CBS_OWNERDRAWFIXED = 16L,
		CBS_OWNERDRAWVARIABLE = 32L,
		CBS_AUTOHSCROLL = 64L,
		CBS_OEMCONVERT = 128L,
		CBS_SORT = 256L,
		CBS_HASSTRINGS = 512L,
		CBS_NOINTEGRALHEIGHT = 1024L,
		CBS_DISABLENOSCROLL = 2048L,
		CBS_UPPERCASE = 8192L,
		CBS_LOWERCASE = 16384L
	}
}
