using System;

namespace OpenDialogs
{
	public enum DialogChangeProperties
	{
		CDM_FIRST = 1124,
		CDM_GETSPEC = 1124,
		CDM_GETFILEPATH,
		CDM_GETFOLDERPATH,
		CDM_GETFOLDERIDLIST,
		CDM_SETCONTROLTEXT,
		CDM_HIDECONTROL,
		CDM_SETDEFEXT
	}
}
