using System;

namespace OpenDialogs
{
	public enum StaticControlStyles : long
	{
		SS_LEFT,
		SS_CENTER,
		SS_RIGHT,
		SS_ICON,
		SS_BLACKRECT,
		SS_GRAYRECT,
		SS_WHITERECT,
		SS_BLACKFRAME,
		SS_GRAYFRAME,
		SS_WHITEFRAME,
		SS_USERITEM,
		SS_SIMPLE,
		SS_LEFTNOWORDWRAP,
		SS_OWNERDRAW,
		SS_BITMAP,
		SS_ENHMETAFILE,
		SS_ETCHEDHORZ,
		SS_ETCHEDVERT,
		SS_ETCHEDFRAME,
		SS_TYPEMASK = 31L,
		SS_REALSIZECONTROL = 64L,
		SS_NOPREFIX = 128L,
		SS_NOTIFY = 256L,
		SS_CENTERIMAGE = 512L,
		SS_RIGHTJUST = 1024L,
		SS_REALSIZEIMAGE = 2048L,
		SS_SUNKEN = 4096L,
		SS_EDITCONTROL = 8192L,
		SS_ENDELLIPSIS = 16384L,
		SS_PATHELLIPSIS = 32768L,
		SS_WORDELLIPSIS = 49152L,
		SS_ELLIPSISMASK = 49152L
	}
}
