using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using CocoStudio.Model.DataModel;

namespace CocoStudio.Model.Lua.Templates
{
	// Token: 0x0200001A RID: 26
	[GeneratedCode("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
	public class LuaGameFileData : LuaNodeObject
	{
		// Token: 0x1700000D RID: 13
		// (get) Token: 0x060000A3 RID: 163 RVA: 0x00005591 File Offset: 0x00003791
		public static string LuaHeader
		{
			get
			{
				return LuaGameFileData.luaHeader;
			}
		}

		// Token: 0x060000A4 RID: 164 RVA: 0x00005598 File Offset: 0x00003798
		public override string TransformText()
		{
			base.Write("--------------------------------------------------------------\n-- This file was automatically generated by Cocos Studio.\n-- Do not make changes to this file.\n-- All changes will be lost.\n--------------------------------------------------------------\n\nlocal luaExtend = require \"LuaExtend\"\n\n-- using for layout to decrease count of local variables\nlocal layout = nil\nlocal localLuaFile = nil\nlocal innerCSD = nil\nlocal innerProject = nil\nlocal localFrame = nil\n\nlocal Result = {}\n------------------------------------------------------------\n-- function call description\n-- create function caller should provide a function to \n-- get a callback function in creating scene process.\n-- the returned callback function will be registered to \n-- the callback event of the control.\n-- the function provider is as below :\n-- Callback callBackProvider(luaFileName, node, callbackName)\n-- parameter description:\n-- luaFileName  : a string, lua file name\n-- node         : a Node, event source\n-- callbackName : a string, callback function name\n-- the return value is a callback function\n------------------------------------------------------------\nfunction Result.create(callBackProvider)\n\nlocal result={}\nsetmetatable(result, luaExtend)\n");
			base.WriteObject(LuaObjectSerializer.GameFileData.ObjectData);
			base.WriteChildren(LuaObjectSerializer.GameFileData.ObjectData);
			this.WriteTimelineAction(LuaObjectSerializer.GameFileData.Animation);
			base.Write("--Create Animation List\r\n");
			this.WriteAnimationList(LuaObjectSerializer.GameFileData.AnimationList);
			base.Write("\r\nresult['root'] = ");
			base.Write(base.ToStringHelper.ToStringWithCulture(base.GetNameString(LuaObjectSerializer.GameFileData.ObjectData.Name)));
			base.Write("\r\nreturn result;\r\nend\r\n\r\nreturn Result\r\n\r\n");
			return base.GenerationEnvironment.ToString();
		}

		// Token: 0x060000A5 RID: 165 RVA: 0x00005644 File Offset: 0x00003844
		private void WriteTimelineAction(TimelineActionData timelineAction)
		{
			ILuaObjectSerializer serializer = LuaObjectManager.GetSerializer(timelineAction);
			if (serializer != null)
			{
				base.Write("\r\n--Create Animation\r\n");
				serializer.CreateObject(timelineAction);
				serializer.InitializeObject(timelineAction);
			}
		}

		// Token: 0x060000A6 RID: 166 RVA: 0x00005674 File Offset: 0x00003874
		private void WriteAnimationList(List<AnimationInfoData> animationList)
		{
			if (animationList == null)
			{
				return;
			}
			AnimationInfoData animationInfoData = animationList.FirstOrDefault<AnimationInfoData>();
			if (animationInfoData == null)
			{
				return;
			}
			ILuaObjectSerializer serializer = LuaObjectManager.GetSerializer(animationInfoData);
			if (serializer == null)
			{
				return;
			}
			foreach (AnimationInfoData animationInfoData2 in animationList)
			{
				serializer.CreateObject(animationInfoData2);
				serializer.InitializeObject(animationInfoData2);
				base.Write("result['animation']:addAnimationInfo(");
				base.Write(base.ToStringHelper.ToStringWithCulture(base.GetNameString(animationInfoData2.Name)));
				base.Write(")\r\n");
			}
		}

		// Token: 0x04000019 RID: 25
		private static readonly string luaHeader = "\n--add LuaScript to search path.\ncc.FileUtils:getInstance():addSearchPath('LuaScript/')\n\n-- used as metaTable\nlocal luaExtend = {}\n\nlocal function getChildInSubNodes(nodeTable, key)\n    if #nodeTable == 0 then\n        return nil\n    end\n    local child = nil\n    local subNodeTable = {}\n    for _, v in ipairs(nodeTable) do\n        child = v:getChildByName(key)\n        if (child) then\n            return child\n        end\n    end\n    for _, v in ipairs(nodeTable) do\n        local subNodes = v:getChildren()\n        if #subNodes ~= 0 then\n            for _, v1 in ipairs(subNodes) do\n                table.insert(subNodeTable, v1)\n            end\n        end\n    end\n    return getChildInSubNodes(subNodeTable, key)\nend\n\nluaExtend.__index = function(table, key)\nlocal root = table.root\nlocal child = root[key]\n    if child then\n        return child\n    end\n\n    child = root:getChildByName(key)\n    if child then\n        root[key] = child\n        return child\n    end\n\n    child = getChildInSubNodes(root:getChildren(), key)\n    if child then root[key] = child end\n    return child\nend\n-- used as metaTable\n\nreturn luaExtend\n";
	}
}
